language: java
jdk:
  - openjdk8

# 모든 브랜치에 일괄 적용하도록 한다.
#branches:
#  only:
#    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# clean 후 Build (Build시 자동으로 test 수행후 jacoco 자동 수행)
script: "./gradlew clean build"