spring:
  profiles:
    active: local

---
spring:
  profiles: prod


---
spring:
  profiles: local
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:peach-bros;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: update